# Generated by Django 3.2.1 on 2021-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('ssn', models.IntegerField()),
                ('age', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
