# Generated by Django 3.2.1 on 2021-05-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0002_useraddress_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityGroup',
            fields=[
                ('priorityid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstavailableslot', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='locationx',
            new_name='locationX',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='locationy',
            new_name='locationY',
        ),
        migrations.AddField(
            model_name='user',
            name='priorityid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
