# Generated by Django 3.2.1 on 2021-05-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0005_rename_covidvaccineprioritydate_prioritydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidvaccinePrioritydate',
            fields=[
                ('priorityid', models.AutoField(primary_key=True, serialize=False)),
                ('slotid', models.IntegerField()),
            ],
            options={
                'db_table': 'CovidVaccine_prioritydate',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PriorityDate',
        ),
        migrations.DeleteModel(
            name='CovidvaccineUser',
        ),
        migrations.DeleteModel(
            name='CovidvaccineUseraddress',
        ),
        migrations.DeleteModel(
            name='CovidvaccineUserlogin',
        ),
    ]
