# Generated by Django 3.2.1 on 2021-05-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0007_auto_20210515_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioritydate',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='useraddress',
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table='userlogin',
        ),
    ]
