# Generated by Django 3.2.1 on 2021-05-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0008_auto_20210515_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidvaccineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ssn', models.IntegerField()),
                ('age', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('prioirtyid', models.IntegerField()),
            ],
            options={
                'db_table': 'CovidVaccine_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CovidvaccineUseraddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('locationx', models.IntegerField()),
                ('locationy', models.IntegerField()),
            ],
            options={
                'db_table': 'CovidVaccine_useraddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CovidvaccineUserlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'CovidVaccine_userlogin',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PriorityDate',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Useraddress',
        ),
        migrations.DeleteModel(
            name='Userlogin',
        ),
    ]
