# Generated by Django 3.2.1 on 2021-05-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0009_auto_20210515_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityDate',
            fields=[
                ('priorityid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ssn', models.IntegerField()),
                ('age', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('prioirtyid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Useraddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('locationx', models.IntegerField()),
                ('locationy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CovidvaccineUser',
        ),
        migrations.DeleteModel(
            name='CovidvaccineUseraddress',
        ),
        migrations.DeleteModel(
            name='CovidvaccineUserlogin',
        ),
    ]
