# Generated by Django 3.2.1 on 2021-05-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0010_auto_20210515_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioritydate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'managed': False},
        ),
    ]
