# Generated by Django 3.2.1 on 2021-05-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0012_auto_20210515_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'provider',
                'managed': False,
            },
        ),
    ]
