# Generated by Django 3.2.1 on 2021-05-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0013_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'managed': True},
        ),
    ]
