# Generated by Django 3.2.1 on 2021-05-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0014_alter_provider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'managed': False},
        ),
    ]
