# Generated by Django 3.2.1 on 2021-05-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0016_distance_provideraddress_timeblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('slotid', models.IntegerField()),
            ],
            options={
                'db_table': 'provider_availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderTravelLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
            options={
                'db_table': 'provider_travel_limit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderWeekLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
            options={
                'db_table': 'provider_week_lock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField()),
                ('slotid', models.IntegerField()),
            ],
            options={
                'db_table': 'user_availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTravelLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
            options={
                'db_table': 'user_travel_limit',
                'managed': False,
            },
        ),
    ]
