# Generated by Django 3.2.1 on 2021-05-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0018_appointment_baduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notacceptedappointment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ssn', models.IntegerField()),
                ('slotid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('user_accepted', models.CharField(max_length=20)),
                ('user_canceled', models.CharField(max_length=20)),
                ('user_showedup', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'notacceptedappointment',
                'managed': False,
            },
        ),
    ]
