# Generated by Django 3.2.1 on 2021-05-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidVaccine', '0020_cancelledappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cancelledappointment',
        ),
    ]
